  version: '3.7'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant:0.102.1
      ports:
        - "8123"
      devices:
        - /dev/ttyACM0
      volumes:
        - /data/homeassistant:/config
        - /data/ssl:/ssl
        - /etc/localtime:/etc/localtime:ro
      dns:
        - 192.168.0.1 
      restart: always
      network_mode: host
