  version: '3.7'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant:stable
      ports:
        - "8123"
      devices:
        - /dev/ttyACM0
      volumes:
        - /data/homeassistant:/config
        - /data/ssl:/ssl
        - /etc/localtime:/etc/localtime:ro
      dns:
        - 192.168.0.1 
      restart: always
      network_mode: host
    mqtt:
      container_name: mqtt
      image: toke/mosquitto
      ports:
        - "1883"
      volumes:
        - /data/mqtt/config:/mqtt/config
        - /data/mqtt/data:/mqtt/data
        - /data/mqtt/log:/mqtt/log
      dns:
        - 192.168.0.1
      restart: always
      network_mode: host

